// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package adder

type requestUserGetUserNameByID struct {
	Id int `json:"id"`
}

type responseUserGetUserNameByID struct {
	Name string `json:"name"`
}
