// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

type requestAdderSum struct {
	AInt int `json:"aInt"`
	BInt int `json:"bInt"`
}

type responseAdderSum struct {
	C int `json:"c"`
}
