// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/rs/zerolog"
	"github.com/sah4ez/tg-example/pkg/interfaces"
)

type httpAdder struct {
	log          zerolog.Logger
	errorHandler ErrorHandler
	svc          *serverAdder
	base         interfaces.Adder
}

func NewAdder(log zerolog.Logger, svcAdder interfaces.Adder) (srv *httpAdder) {

	srv = &httpAdder{
		base: svcAdder,
		log:  log,
		svc:  newServerAdder(svcAdder),
	}
	return
}

func (http httpAdder) Service() MiddlewareSetAdder {
	return http.svc
}

func (http *httpAdder) WithLog(log zerolog.Logger) *httpAdder {
	http.svc.WithLog(log)
	return http
}

func (http *httpAdder) WithErrorHandler(handler ErrorHandler) *httpAdder {
	http.errorHandler = handler
	return http
}

func (http *httpAdder) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/adder", http.serveBatch)
	route.Post("/api/v1/adder/add", http.serveAdd)
}
