// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

type requestAdderSum struct {
	AInt int `json:"aInt,omitempty"`
	BInt int `json:"bInt,omitempty"`
}

type responseAdderSum struct {
	C int `json:"c,omitempty"`
}
