// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

// Formal exchange type, please do not delete.
type requestFilesGetTemplate struct{}

type responseFilesGetTemplate struct {
	Data []byte `json:"data,omitempty"`
	Name string `json:"name,omitempty"`
}
