// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/tg-example/pkg/interfaces"
)

type FilesGetTemplate func(ctx context.Context) (data []byte, name string, err error)

type MiddlewareFiles func(next interfaces.Files) interfaces.Files

type MiddlewareFilesGetTemplate func(next FilesGetTemplate) FilesGetTemplate
