// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"context"

	"github.com/sah4ez/tg-example/pkg/interfaces"
)

type UserGetUserNameByID func(ctx context.Context, id int) (name string, err error)

type MiddlewareUser func(next interfaces.User) interfaces.User

type MiddlewareUserGetUserNameByID func(next UserGetUserNameByID) UserGetUserNameByID
