// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package transport

import (
	"github.com/gofiber/fiber/v2"
	"github.com/rs/zerolog"
	"github.com/sah4ez/tg-example/pkg/interfaces"
)

type httpUser struct {
	log          zerolog.Logger
	errorHandler ErrorHandler
	svc          *serverUser
	base         interfaces.User
}

func NewUser(log zerolog.Logger, svcUser interfaces.User) (srv *httpUser) {

	srv = &httpUser{
		base: svcUser,
		log:  log,
		svc:  newServerUser(svcUser),
	}
	return
}

func (http httpUser) Service() MiddlewareSetUser {
	return http.svc
}

func (http *httpUser) WithLog(log zerolog.Logger) *httpUser {
	http.svc.WithLog(log)
	return http
}

func (http *httpUser) WithErrorHandler(handler ErrorHandler) *httpUser {
	http.errorHandler = handler
	return http
}

func (http *httpUser) SetRoutes(route *fiber.App) {
	route.Post("/api/v1/user", http.serveBatch)
	route.Post("/api/v1/user/getUserNameByID", http.serveGetUserNameByID)
}
