// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package user

import (
	"context"
	"fmt"

	"github.com/sah4ez/tg-example/pkg/clients/user/hasher"
	"github.com/sah4ez/tg-example/pkg/clients/user/jsonrpc"
)

type ClientUser struct {
	*ClientJsonRPC
}

type retUserGetUserNameByID = func(name string, err error)

func (cli *ClientUser) GetUserNameByID(ctx context.Context, id int) (name string, err error) {

	request := requestUserGetUserNameByID{Id: id}
	var response responseUserGetUserNameByID
	var rpcResponse *jsonrpc.ResponseRPC
	cacheKey, _ := hasher.Hash(request)
	rpcResponse, err = cli.rpc.Call(ctx, "user.getusernamebyid", request)
	var fallbackCheck func(error) bool
	if cli.fallbackUser != nil {
		fallbackCheck = cli.fallbackUser.GetUserNameByID
	}
	if rpcResponse != nil && rpcResponse.Error != nil {
		if cli.errorDecoder != nil {
			err = cli.errorDecoder(rpcResponse.Error.Raw())
		} else {
			err = fmt.Errorf(rpcResponse.Error.Message)
		}
	}
	if err = cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response); err != nil {
		return
	}
	return response.Name, err
}

func (cli *ClientUser) ReqGetUserNameByID(ctx context.Context, callback retUserGetUserNameByID, id int) (request RequestRPC) {

	request = RequestRPC{rpcRequest: &jsonrpc.RequestRPC{
		ID:      jsonrpc.NewID(),
		JSONRPC: jsonrpc.Version,
		Method:  "user.getusernamebyid",
		Params:  requestUserGetUserNameByID{Id: id},
	}}
	if callback != nil {
		var response responseUserGetUserNameByID
		request.retHandler = func(err error, rpcResponse *jsonrpc.ResponseRPC) {
			cacheKey, _ := hasher.Hash(request.rpcRequest.Params)
			var fallbackCheck func(error) bool
			if cli.fallbackUser != nil {
				fallbackCheck = cli.fallbackUser.GetUserNameByID
			}
			if rpcResponse != nil && rpcResponse.Error != nil {
				if cli.errorDecoder != nil {
					err = cli.errorDecoder(rpcResponse.Error.Raw())
				} else {
					err = fmt.Errorf(rpcResponse.Error.Message)
				}
			}
			callback(response.Name, cli.proceedResponse(ctx, err, cacheKey, fallbackCheck, rpcResponse, &response))
		}
	}
	return
}
