// GENERATED BY 'T'ransport 'G'enerator. DO NOT EDIT.
package user

type requestUserGetUserNameByID struct {
	Id int `json:"id,omitempty"`
}

type responseUserGetUserNameByID struct {
	Name string `json:"name,omitempty"`
}
